version: "3.8"
services:
  lottery_web:
    image: lottery_web_image
    build: .
    ports:
      - "3010:3000"
    restart: always
    volumes:
      - .:/usr/src/lottery_web
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
